services:
  postgres:
    image: postgres:15
    container_name: users_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bank_postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BANK_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${BANK_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users_service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    container_name: bank_service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: bank_postgres
      DB_NAME: ${BANK_DB_NAME}
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8080"
    depends_on:
      bank_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  bank_postgres_data:
